AWSTemplateFormatVersion: '2010-09-09'
Resources:
  NotasFiscaisAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: NotasFiscaisAPI
  NotasResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: { "Fn::GetAtt": [ "NotasFiscaisAPI", "RootResourceId" ] }
      PathPart: notas
      RestApiId: { "Ref": "NotasFiscaisAPI" }
  PostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: { "Ref": "NotasFiscaisAPI" }
      ResourceId: { "Ref": "NotasResource" }
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:ProcessarNotasFiscais/invocations
  GetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: { "Ref": "NotasFiscaisAPI" }
      ResourceId: { "Ref": "NotasResource" }
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:ProcessarNotasFiscais/invocations

